# Use the Nginx image from Docker Hub
FROM nginx

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the configuration file from the local directory
COPY iac/django/nginx.conf /etc/nginx/conf.d/default.conf

# Add a command to print the file contents
RUN cat /etc/nginx/conf.d/default.conf
