# Generated by Django 4.2.2 on 2023-06-22 06:47

from django.db import migrations


def create_default_documentcollection(apps, schema_editor):
    from ..vectorstore import create_vectorstore_collection

    slug = 'default'
    DocumentCollection = apps.get_model('documents', 'DocumentCollection')
    DocumentCollection.objects.create(
        name='default',
        slug=slug,
        description='Default document collection',
    )
    create_vectorstore_collection(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcollection_unstructureddocument_collection'),
    ]

    operations = [
        migrations.RunPython(create_default_documentcollection),
    ]
