#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# On startup, we roll the database forward to the latest migration
# before starting the server.
alembic upgrade head
uvicorn main:app --reload --reload-dir martini --host 0.0.0.0
